### ISSUE TITLE
Fitting Linear Model

### ISSUE THREAD

**Issue by RipeNishtala** [dnanexus/UKB_RAP#38]
Hi Alex
Is there a reason why the model was not fitted with npx_normalised data?
many thanks
prasad

**Comment by ajlee21** [comment]
Hi Prasad,
Do you mind providing a bit more context here - Which notebook are you referring to?

**Comment by RipeNishtala** [comment]
Hi Alex
I am referring to the proteomics differential expression analyses. You fitted a linear model using the limma package on npx data ( protein markers) rather than the npx normalised data.
I am driving home but can send you more info on Monday morning
Bw
Prasad

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by RipeNishtala** [comment]
Hi Alex,
Here is the link: https://github.com/dnanexus/UKB_RAP/tree/main/proteomics/protein_DE_analysis
# lmFit expects input array to have structure: protein x sample
# lmFit fits a linear model using weighted least squares for each protein:
fit <- lmFit(t(npx_df), design)

As you can see in ln 22, you have fit the linear model using npx_df rather than npx_normalized data.
Apologies if I misunderstood this. I thought we mitigate proteins with huge ranges as they will likely dominate the results.

Yor clarification would be much appreciated.
BW
prasad

**Comment by ajlee21** [comment]
Great question!

From my understanding it doesn't seem like there is a standard methodology for processing the data and using normalization. For the most part folks seem to be adapting techniques from RNAseq/array data. In this case I didn't normalize the NPX values since it was on log2 scale, similar to array data where I don't believe additional scaling is performed prior to DE. Additionally, if I compare the DE results using with and without normalization there isn't much difference in the number of proteins found.

As for proteins with large levels of activity, I don't think this should affect the likelihood of other proteins found to be DE since each protein is treated independently.

Please let me know if this makes sense

**Comment by RipeNishtala** [comment]
Many thanks for the clarification. Great work! & i found it very informative.
Best wishes
prasad

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
